version: '2'
services:
  api:
    build: noteboard-api
    image: emaraschio/noteboard-api
    volumes:
      - ./noteboard-api:/usr/src/app
    ports:
      - "3000:3000"
  client:
    build: noteboard-client
    image: emaraschio/noteboard-client
    volumes:
      - ./noteboard-client:/app
    ports:
      - "4000:4000"
    environment:
     - REACT_APP_API_URL=http://localhost:3000